// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: linkedon/linkedon.proto

package linkedon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LinkedonService_CreatePerson_FullMethodName = "/linkedon.LinkedonService/CreatePerson"
	LinkedonService_Connect_FullMethodName      = "/linkedon.LinkedonService/Connect"
)

// LinkedonServiceClient is the client API for LinkedonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkedonServiceClient interface {
	CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
}

type linkedonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkedonServiceClient(cc grpc.ClientConnInterface) LinkedonServiceClient {
	return &linkedonServiceClient{cc}
}

func (c *linkedonServiceClient) CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePersonResponse)
	err := c.cc.Invoke(ctx, LinkedonService_CreatePerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkedonServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, LinkedonService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkedonServiceServer is the server API for LinkedonService service.
// All implementations must embed UnimplementedLinkedonServiceServer
// for forward compatibility.
type LinkedonServiceServer interface {
	CreatePerson(context.Context, *CreatePersonRequest) (*CreatePersonResponse, error)
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	mustEmbedUnimplementedLinkedonServiceServer()
}

// UnimplementedLinkedonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLinkedonServiceServer struct{}

func (UnimplementedLinkedonServiceServer) CreatePerson(context.Context, *CreatePersonRequest) (*CreatePersonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePerson not implemented")
}
func (UnimplementedLinkedonServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedLinkedonServiceServer) mustEmbedUnimplementedLinkedonServiceServer() {}
func (UnimplementedLinkedonServiceServer) testEmbeddedByValue()                         {}

// UnsafeLinkedonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkedonServiceServer will
// result in compilation errors.
type UnsafeLinkedonServiceServer interface {
	mustEmbedUnimplementedLinkedonServiceServer()
}

func RegisterLinkedonServiceServer(s grpc.ServiceRegistrar, srv LinkedonServiceServer) {
	// If the following call panics, it indicates UnimplementedLinkedonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LinkedonService_ServiceDesc, srv)
}

func _LinkedonService_CreatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkedonServiceServer).CreatePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkedonService_CreatePerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkedonServiceServer).CreatePerson(ctx, req.(*CreatePersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkedonService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkedonServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkedonService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkedonServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LinkedonService_ServiceDesc is the grpc.ServiceDesc for LinkedonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinkedonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linkedon.LinkedonService",
	HandlerType: (*LinkedonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePerson",
			Handler:    _LinkedonService_CreatePerson_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _LinkedonService_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "linkedon/linkedon.proto",
}
