// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: linkedon/linkedon.proto

package linkedon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_linkedon_linkedon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_linkedon_linkedon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_linkedon_linkedon_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreatePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonRequest) Reset() {
	*x = CreatePersonRequest{}
	mi := &file_linkedon_linkedon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonRequest) ProtoMessage() {}

func (x *CreatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkedon_linkedon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return file_linkedon_linkedon_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePersonRequest) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type FollowPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int32                  `protobuf:"varint,1,opt,name=followerId,proto3" json:"followerId,omitempty"`
	FolloweeId    int32                  `protobuf:"varint,2,opt,name=followeeId,proto3" json:"followeeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowPersonRequest) Reset() {
	*x = FollowPersonRequest{}
	mi := &file_linkedon_linkedon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowPersonRequest) ProtoMessage() {}

func (x *FollowPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkedon_linkedon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowPersonRequest.ProtoReflect.Descriptor instead.
func (*FollowPersonRequest) Descriptor() ([]byte, []int) {
	return file_linkedon_linkedon_proto_rawDescGZIP(), []int{2}
}

func (x *FollowPersonRequest) GetFollowerId() int32 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *FollowPersonRequest) GetFolloweeId() int32 {
	if x != nil {
		return x.FolloweeId
	}
	return 0
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_linkedon_linkedon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkedon_linkedon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_linkedon_linkedon_proto_rawDescGZIP(), []int{3}
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Extra         string                 `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_linkedon_linkedon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_linkedon_linkedon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_linkedon_linkedon_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

var File_linkedon_linkedon_proto protoreflect.FileDescriptor

const file_linkedon_linkedon_proto_rawDesc = "" +
	"\n" +
	"\x17linkedon/linkedon.proto\x12\blinkedon\">\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\"?\n" +
	"\x13CreatePersonRequest\x12(\n" +
	"\x06person\x18\x01 \x01(\v2\x10.linkedon.PersonR\x06person\"U\n" +
	"\x13FollowPersonRequest\x12\x1e\n" +
	"\n" +
	"followerId\x18\x01 \x01(\x05R\n" +
	"followerId\x12\x1e\n" +
	"\n" +
	"followeeId\x18\x02 \x01(\x05R\n" +
	"followeeId\"\x0e\n" +
	"\fResetRequest\":\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05extra\x18\x02 \x01(\tR\x05extra2\xcc\x01\n" +
	"\x0fLinkedonService\x12A\n" +
	"\fCreatePerson\x12\x1d.linkedon.CreatePersonRequest\x1a\x12.linkedon.Response\x12A\n" +
	"\fFollowPerson\x12\x1d.linkedon.FollowPersonRequest\x1a\x12.linkedon.Response\x123\n" +
	"\x05Reset\x12\x16.linkedon.ResetRequest\x1a\x12.linkedon.ResponseB$Z\"github.com/orens/linkedon/linkedonb\x06proto3"

var (
	file_linkedon_linkedon_proto_rawDescOnce sync.Once
	file_linkedon_linkedon_proto_rawDescData []byte
)

func file_linkedon_linkedon_proto_rawDescGZIP() []byte {
	file_linkedon_linkedon_proto_rawDescOnce.Do(func() {
		file_linkedon_linkedon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_linkedon_linkedon_proto_rawDesc), len(file_linkedon_linkedon_proto_rawDesc)))
	})
	return file_linkedon_linkedon_proto_rawDescData
}

var file_linkedon_linkedon_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_linkedon_linkedon_proto_goTypes = []any{
	(*Person)(nil),              // 0: linkedon.Person
	(*CreatePersonRequest)(nil), // 1: linkedon.CreatePersonRequest
	(*FollowPersonRequest)(nil), // 2: linkedon.FollowPersonRequest
	(*ResetRequest)(nil),        // 3: linkedon.ResetRequest
	(*Response)(nil),            // 4: linkedon.Response
}
var file_linkedon_linkedon_proto_depIdxs = []int32{
	0, // 0: linkedon.CreatePersonRequest.person:type_name -> linkedon.Person
	1, // 1: linkedon.LinkedonService.CreatePerson:input_type -> linkedon.CreatePersonRequest
	2, // 2: linkedon.LinkedonService.FollowPerson:input_type -> linkedon.FollowPersonRequest
	3, // 3: linkedon.LinkedonService.Reset:input_type -> linkedon.ResetRequest
	4, // 4: linkedon.LinkedonService.CreatePerson:output_type -> linkedon.Response
	4, // 5: linkedon.LinkedonService.FollowPerson:output_type -> linkedon.Response
	4, // 6: linkedon.LinkedonService.Reset:output_type -> linkedon.Response
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_linkedon_linkedon_proto_init() }
func file_linkedon_linkedon_proto_init() {
	if File_linkedon_linkedon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_linkedon_linkedon_proto_rawDesc), len(file_linkedon_linkedon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_linkedon_linkedon_proto_goTypes,
		DependencyIndexes: file_linkedon_linkedon_proto_depIdxs,
		MessageInfos:      file_linkedon_linkedon_proto_msgTypes,
	}.Build()
	File_linkedon_linkedon_proto = out.File
	file_linkedon_linkedon_proto_goTypes = nil
	file_linkedon_linkedon_proto_depIdxs = nil
}
